### ISSUE TITLE
Návrhové vzory - creational design patterns, structural design patterns, behavioral patterns

### ISSUE THREAD

**Issue by OndrejKulhavy** [OndrejKulhavy/MaturitaJecna#13]

**Comment by OndrejKulhavy** [comment]
### Preview Youtube thumbnail


![Image](https://github.com/OndrejKulhavy/MaturitaJecna/assets/48098372/21d61b57-33c5-43da-b981-46b47c1510e1)

**Comment by MaksymDoremi** [comment]
docookovano
[Navrhove_vzory.md](https://github.com/OndrejKulhavy/MaturitaJecna/files/13964694/Navrhove_vzory.md)

**Comment by OndrejKulhavy** [comment]
1. Co to je a proc se to pouziva?
2. Jejich druhy
3. Creational design patterns
4. Structural design patterns
5. Behavioral patterns

**Comment by MaksymDoremi** [comment]
https://github.com/MaksymDoremi/CreationalStructuralBehavioralDesignPatterns

GITHUB REPO
