### ISSUE TITLE
Soubory a serializace - Ukládání a načítání dat, formáty souborů

### ISSUE THREAD

**Issue by OndrejKulhavy** [OndrejKulhavy/MaturitaJecna#16]

**Comment by JirkS** [comment]
https://docs.google.com/document/d/19kHp2x9rmQ3eAilzbuWsMP0pRwSU-TJRF9iQYdgF7Eg/edit#heading=h.t0jsflun45cj

**Comment by MaksymDoremi** [comment]
Zkontrolováno.
Spracování velmi dobré.
Body k maturitě:
1. Co je vlastně soubor? 
     Uložení dat na dobu delší než běh programu.

2.using (StreamReader reader = new StreamReader("example.txt")){}, 
      using je pro otevření souboru a následně pro zavření, bez implicitního využití Open() a Close()

3.using (StreamWriter writer = new StreamWriter("output.txt"))

4.Alternativa na práci se soubory je File.metody… což jsou statické metody, 
      je to jednodušší na použití (ChatGPT: “In summary, File.WriteAllText() is simpler and more straightforward for basic text writing 
      operations, while StreamWriter offers more control and flexibility for advanced scenarios.”)

5.Serializace - převedení na stream bytů pro delší uložení, Deserializace - zpětně.

6.Ukázat XmlSerializer, je to simple, udělejte třídu Psa, kohokoliv a 
      XmlSerializer serializer = new XmlSerializer(typeof(Dog)); 
      následně serializer.Serialize(writer, dog); 


Schváleno,
Maksym Kintor
