### ISSUE TITLE
Testování, Unit testování a dokumentace zdrojového kódu

### ISSUE THREAD

**Issue by OndrejKulhavy** [OndrejKulhavy/MaturitaJecna#20]

**Comment by OndrejKulhavy** [comment]
### Preview Youtube thumbnail


![Image](https://github.com/OndrejKulhavy/MaturitaJecna/assets/48098372/01c3da3e-31aa-46b1-88a1-d80176814241)

**Comment by cesarjakub** [comment]
jdu na to!

**Comment by MaksymDoremi** [comment]
jasan draku

**Comment by cesarjakub** [comment]
[Uploading Testování,_Unit_testování_a_dokumentace_zdrojového_kódu.md…]()

**Comment by cesarjakub** [comment]
[Testování,_Unit_testování_a_dokumentace_zdrojového_kódu.md](https://github.com/OndrejKulhavy/MaturitaJecna/files/13661937/Testovani._Unit_testovani_a_dokumentace_zdrojoveho_kodu.md)

**Comment by cesarjakub** [comment]
new version

[Testování,_Unit_testování_a_dokumentace_zdrojového_kódu.md](https://github.com/OndrejKulhavy/MaturitaJecna/files/13662096/Testovani._Unit_testovani_a_dokumentace_zdrojoveho_kodu.md)

**Comment by MaksymDoremi** [comment]
Změnená struktura white box a black  box testů, rozřazeno do stromové struktury, některé informace byly zbytečně, takže se vymazaly. Také opraveny maličke překliky, chyby.
Schvaluji.


Reviewers: @Kalash004, @MaksymDoremi 

[Testovani._Unit_testovani_a_dokumentace_zdrojoveho_kodu.md](https://github.com/OndrejKulhavy/MaturitaJecna/files/14039440/Testovani._Unit_testovani_a_dokumentace_zdrojoveho_kodu.md)

**Comment by Kalash004** [comment]
Done, review @Kalash004, @MaksymDoremi

**Comment by OndrejKulhavy** [comment]
Přidáno:

- 7 bodů
- video

[Testovani._Unit_testovani_a_dokumentace_zdrojoveho_kodu.md](https://github.com/OndrejKulhavy/MaturitaJecna/files/14195055/Testovani._Unit_testovani_a_dokumentace_zdrojoveho_kodu.md)

**Comment by MaksymDoremi** [comment]
1. **Co je testování a jakou roli hraje ve vývoji softwaru?**

   - Testování je proces, který zajišťuje bezpečnost a funkčnost produktu během vývoje softwaru. Hraje klíčovou roli při ověřování, zda je software v souladu s požadavky zákazníka a zda je kód funkční.

2. **Jak testování přispívá k zajištění kvality a funkčnosti kódu?**

   - Testování kontroluje splnění všech funkčních požadavků zákazníka a zajišťuje, že kód je funkční a bezpečný. Tím přispívá k vytvoření kvalitního a spolehlivého produktu.

3. **Proč je důležitá dokumentace při vývoji softwaru a jaký účel má?**

   - Dokumentace slouží k zajištění pochopení kódu před nasazením do ostrého provozu. Poskytuje srozumitelný popis kódu pro budoucí programátory a zvyšuje životnost a udržitelnost produktu.

4. **Podle jakých parametrů se hodnotí kvalita testování?**

   - Kvalita testování se hodnotí podle různých dimenzí, jako jsou funkčnost, použitelnost, spolehlivost, výkon, bezpečnost, kompatibilita a přenositelnost.

5. **Jaké jsou hlavní typy testování a jak se liší?**

   - Hlavními typy testování jsou white box testování a black box testování. White box testování testuje interní implementaci kódu, zatímco black box testování testuje pouze externí design systému.

6. **Co zahrnuje unit testování a jaké jsou jeho klíčové prvky?**

   - Unit testování zahrnuje testování nejmenších testovatelných jednotek kódu a ověřuje, že se chovají správně nezávisle na ostatních částech systému. Klíčovými prvky jsou izolace testované jednotky a ověření jejího správného chování.

7. **Jak unit testy naimplementovat?**
   - Správná implementace unit testů v jazyce C# zajišťuje kvalitu a spolehlivost kódu. Obvyklé postupy zahrnují použití testovacích frameworků, jako jsou MSTest, NUnit nebo xUnit, a vytváření samostatných testovacích tříd s označenými testovacími metodami.
