### ISSUE TITLE
Typy datových struktur - Pole, Spojový seznam, Strom, Fronta, Zásobník, Halda

### ISSUE THREAD

**Issue by OndrejKulhavy** [OndrejKulhavy/MaturitaJecna#21]

**Comment by OndrejKulhavy** [comment]
### Preview Youtube thumbnail



![Image](https://github.com/OndrejKulhavy/MaturitaJecna/assets/48098372/58af1769-f2a9-4869-b9ee-552378af4438)

**Comment by cesarjakub** [comment]
[https://docs.google.com/document/d/1qKluPfOheCgq5nwDt-TfN_WBrCs0deLIVmKDyBWxG2w/edit](https://docs.google.com/document/d/1qKluPfOheCgq5nwDt-TfN_WBrCs0deLIVmKDyBWxG2w/edit)

**Comment by Kalash004** [comment]
Changes : One Way / Both Ways Linked lists - changed important information and naming

**Comment by Kalash004** [comment]
Changes for Trees

**Comment by MaksymDoremi** [comment]
Viz @Kalash004 byly provedeny úpravy,
Schváleno


Reviewers: @Kalash004, @MaksymDoremi 

https://docs.google.com/document/d/1qKluPfOheCgq5nwDt-TfN_WBrCs0deLIVmKDyBWxG2w/edit

**Comment by Kalash004** [comment]
přidat kód pro linkedlist

**Comment by MaksymDoremi** [comment]
Pridano

**Comment by MaksymDoremi** [comment]
https://github.com/MaksymDoremi/TypyDatovychStruktur
GITHUB REPO
