### ISSUE TITLE
Vlastnosti datových struktur - Seřazenost a opakování prvků, Indexace, hashování a klíče prvků

### ISSUE THREAD

**Issue by OndrejKulhavy** [OndrejKulhavy/MaturitaJecna#23]

**Comment by OndrejKulhavy** [comment]
### Preview Youtube thumbnail



![Image](https://github.com/OndrejKulhavy/MaturitaJecna/assets/48098372/9db772e3-06fb-4527-b6b0-d4a4ab77c655)

**Comment by JirkS** [comment]
https://docs.google.com/document/d/13ASPGTOMrn1qpAEScQK-4FNwX7auafHKqf2tAFoE3VQ/edit#heading=h.uudsbp8v0oc1

**Comment by MaksymDoremi** [comment]
Provedena kontrola.
Vypracování je smyslúplné, správné.
Body k maturitě:

1. Data structure - vysvětlení v pár slovech.
2. Seřazenost, opakování - vysvětlit česky
3. Indexy, klíče - přístup k prvku konstantní
4. Hashování - unikátní číslo na základě hodnot daných
5. Klíče - unikátní hodnota pro rychlý, konstantní přístup k objektu
6. Ukázat na příkladě pár basic struktur, provést for loop viz. tabulka dole



Schváleno.
Maksym Kintor

**Comment by MaksymDoremi** [comment]
https://github.com/MaksymDoremi/VlastnostiDatovychStruktur
GITHUB REPO

Nektere veci jsem nepsal, ackoliv jsou primitivni a to vsichni umime
