### ISSUE TITLE
Zpracování a parsování textových dat, regulární výrazy, kódování a stringy

### ISSUE THREAD

**Issue by OndrejKulhavy** [OndrejKulhavy/MaturitaJecna#25]

**Comment by OndrejKulhavy** [comment]
### Koncept... Youtube thumbnail

![Image](https://github.com/OndrejKulhavy/MaturitaJecna/assets/48098372/df3af64c-1213-43ac-b388-e0eabd20722a)

**Comment by JirkS** [comment]
https://docs.google.com/document/d/1ly3foC1IXWL6Zrr7CqUZWvH-ZACOce4cg2vckXSTQRo/edit#heading=h.t0jsflun45cj
