### ISSUE TITLE
Algoritmizace - Rekurze, Brute Force, Heuristiky, Nedeterministické algoritmy

### ISSUE THREAD

**Issue by OndrejKulhavy** [OndrejKulhavy/MaturitaJecna#3]

**Comment by OndrejKulhavy** [comment]
### Preview Youtube thumbnail

![Image](https://github.com/OndrejKulhavy/MaturitaJecna/assets/48098372/0214e3c2-4fe0-4ae0-9cc4-6be7d3f8cefe)

**Comment by MaksymDoremi** [comment]
https://docs.google.com/document/d/1Z1mk8VkzLn8a2J-xEXo3N8feAXgpvCxSLi8BvoqtfCQ/edit#heading=h.nn44dyxi3q99

**Comment by MaksymDoremi** [comment]
pridany body

cooked
