### ISSUE TITLE
Architectural design patterns - MVC, Multitier, Monolithic, P2P, Client/Server

### ISSUE THREAD

**Issue by OndrejKulhavy** [OndrejKulhavy/MaturitaJecna#5]

**Comment by OndrejKulhavy** [comment]
### Preview Youtube thumbnail


![Image](https://github.com/OndrejKulhavy/MaturitaJecna/assets/48098372/c64519f2-ff0d-444c-aaee-53d36c6efe8e)

**Comment by JirkS** [comment]
https://docs.google.com/document/d/1Bg4NXcmTAIwVlQYnzBdJYeuweggNtwSVYGihqbwbb3g/edit

**Comment by MaksymDoremi** [comment]
Schváleno

Maksym Kintor


Body k maturitě
1. Architektonické design patterny - říct česky, způsob návrhu software podle konvencí, co lidé vymysleli, za účelem dlouhé životnosti kodu, readability, updateability
2. Monolithic - všechno do jednoho, pro malé projekty je to velmi výhodné, velké projekty zas na tom prodělají - říct proč…
3. MVC - rozdělení do tří části, Model, View a Controller, což je velmi výhodné pro velké projekty, je to škálovatelný, modulární a velice udržitelný, malé projekty nemají smysl implementovat MVC - náročný na implementaci. Je to triangular pattern, View může komunikovat s Modelem.
4. Multi(Three)-tier - většinou se dělí do 3 části, jeden rozdíl od MVC je to že prezentační vrstva nekomunikuje přímo s databázi. Je to linear pattern, Presentation tier, Business tier a Data tier.
5. P2P - připojení jednoho zařízení k jinému, nikdo není nadřazený jinému, oboje jsou konzumery a producenty, decentralizovaný systém ale issues s bezpečnosti.
6. Client/Server - hodně klientů, jeden server. Centralizovaný systém, větší bezpečnost, vyšší škálovatelnost.
7. Ukázat nějaký basic kod.

**Comment by MaksymDoremi** [comment]
za me tady toho kodu moc nebude, takze stick to 3 minutes talk pro kazde, trochu obrazku, pripadne kdyz staci cas tak nejaky sketch code
