### ISSUE TITLE
Asymptotické paměťové a časové složitosti

### ISSUE THREAD

**Issue by OndrejKulhavy** [OndrejKulhavy/MaturitaJecna#6]

**Comment by JirkS** [comment]
https://docs.google.com/document/d/132B09eW-jMgJJbg_cXcx6m3SuCnmkXotb1FfWmzuhWQ/edit#heading=h.amyl2fkhati9

**Comment by MaksymDoremi** [comment]
pridano big o notation ke kazde slozitosti
