### ISSUE TITLE
Datové typy, Generika, Výčtové datové typy, Struktury, Anotace, Operátory

### ISSUE THREAD

**Issue by OndrejKulhavy** [OndrejKulhavy/MaturitaJecna#7]

**Comment by MaksymDoremi** [comment]
Zkontrolováno.
https://docs.google.com/document/d/1T3JcQlNov82W1yIYlp8JuDE526mQCZuu9-BmZyj8lEU/edit
Dokument obsahuje popisy lidského typu, tedy pro lepši pochopení.
Za mě legit informace.
Schvalují.


Maksym Kintor
