### ISSUE TITLE
Dědičnost, method overriding, function overloading

### ISSUE THREAD

**Issue by OndrejKulhavy** [OndrejKulhavy/MaturitaJecna#8]

**Comment by OndrejKulhavy** [comment]
### Preview Youtube thumbnail



![Image](https://github.com/OndrejKulhavy/MaturitaJecna/assets/48098372/d66dfd6c-d010-4710-b2fa-4528f14f0140)

**Comment by erikbohac** [comment]
Chybí Polymorfismus + ukázka kódu

**Comment by OndrejKulhavy** [comment]
https://docs.google.com/document/d/1CYbf5t4FPqHxRY0cLRrxgaYb4S5rtX1aW8A4YoXfTLc/edit?usp=sharing

**Comment by erikbohac** [comment]
třeba přepsat do markdown

**Comment by MaksymDoremi** [comment]
Přidáno nový odstavec ohledně **Protected** vlastnosti tříd v rámci **Inheritance**
Jinak za mě v pohodě.
Schvalují


Maksym Kintor

**Comment by MaksymDoremi** [comment]
Pridano github repo
