### ISSUE TITLE
Integrita dat, bezpečnost, logování, kontrola vstupů, zpracování chyb

### ISSUE THREAD

**Issue by OndrejKulhavy** [OndrejKulhavy/MaturitaJecna#9]

**Comment by JirkS** [comment]
https://docs.google.com/document/d/1MJGCCGlVjvlz4SrE_w9kXCneO2IDql9i4wCqd4maMmc/edit#heading=h.t0jsflun45cj nejak jsem to splacel

**Comment by MaksymDoremi** [comment]
Hele Jirko super prace, ted na to pravve koukam
